#!/system/bin/sh

export PATH="/system/xbin:/system/bin";
#export HOME="/sdcard/";
export BOOT_DIR=$(realpath $2 2>/dev/null);

NO_ERROR=0;
ENV_ERROR=1;
PERM_ERR=2;
BOOT_ERR=3;

type busybox > /dev/null 2>&1 || {
  echo "Not found busybox!";
  echo "Check you path and try again!";
  exit $ENV_ERROR;
};

show_help()
{
cat <<HELP
temrix - a script to run linux on termux.

Usage: ${0##*/} <init|boot> <bootdir>

See also:
  QQGroup: 494453985
  https://github.com/95e2/linux-on-termux
HELP
}

check_env()
{
  if [ $(id -u) != 0 ]; then
    echo "This termix can only be run as root!";
    exit $PERM_ERR;
  fi;
  if [ ! -e $BOOT_DIR ] || [ x$BOOT_DIR = "x" ]; then
    echo "Not found path [$BOOT_DIR]!";
    exit $ENV_ERROR;
  fi;
  if [ "$(cd $BOOT_DIR; pwd)" = "$(pwd)" ]; then
    echo "\$BOOT_DIR can not be \$PWD!";
    exit $ENV_ERROR;
  fi; [ "$BOOT_DIR" = "/" ] && exit $ENV_ERROR;
}

termix_init()
{
cat > $BOOT_DIR/init.sh <<INIT
#!/bin/sh

unset PREFIX TMPDIR HOME SHELL;
unset LD_LIBRARY_PATH HISTFILE;
unset ANDROID_ROOT ANDROID_DATA;
unset EXTERNAL_STORAGE LD_PRELOAD;

export TERM="xterm";
export HOME="/root";
export PATH="/bin:/sbin:/usr/bin:/usr/sbin";
export PATH="\$PATH:/usr/local/bin:/opt/bin";

# Preload profile
. /etc/profile;

# Show logo, even though it was crashed.
echo " _____                   _      ";
echo "|_   _|__ _ __ _ __ ___ (_)_  __";
echo "  | |/ _ \\\ '__| '_ \\\` _ \\\| \\\ \\\/ /";
echo "  | |  __/ |  | | | | | | |>  < ";
echo "  |_|\\\___|_|  |_| |_| |_|_/_/\\\_\\\ v1.2.3";
echo "                                ";
echo " A chroot scripts to run linux on termux.";

sh -l; exit \$?
#su - root; exit \$?;
INIT
}

termix_boot()
{
  unset LD_PRELOAD;
  export PATH="/system/xbin";
  if [ ! -e $BOOT_DIR/init.sh ]; then
    echo "Not found [$BOOT_DIR/init.sh]";
    echo "Have you run termix init?";
    exit $BOOT_ERR;
  fi; chmod -f 755 $BOOT_DIR/init.sh;
  
  if [ ! -e $BOOT_DIR/isMounted ]; then
    mount -o remount,suid /data;
    mount --rbind /dev $BOOT_DIR/dev;
    mount --rbind /proc $BOOT_DIR/proc;
    mount --rbind /sys $BOOT_DIR/sys;
    mount tmpfs -t tmpfs -o size="50%" $BOOT_DIR/tmp;
    touch $BOOT_DIR/isMounted;
  
    if [ -e /data/data/com.termux ]; then
      if [ ! -e $BOOT_DIR/sdcard ]; then
        mkdir $BOOT_DIR/sdcard;
        chmod 755 $BOOT_DIR/sdcard;
      fi;
      mount --bind /sdcard $BOOT_DIR/sdcard;
    fi;
  
    # Fix DNS
    if [ ! -e $BOOT_DIR/etc/resolv.conf.ok ]; then
      rm -rf $BOOT_DIR/resolv.conf;
      echo "nameserver 8.8.8.8" > \
               $BOOT_DIR/etc/resolv.conf;
      echo "DNS IS OK" > $BOOT_DIR/etc/resolv.conf.ok;
    fi;
    chroot $BOOT_DIR /init.sh; ret=$?;
  
    # Clean up
    rm -rf $BOOT_DIR/tmp/*; fuser -k $BOOT_DIR;
    cat /proc/mounts | awk '{ print $2 }' | \
          grep "^$BOOT_DIR"| grep -v "^$BOOT_DIR\$" | \
                           sort -u -r | xargs umount;
    rm $BOOT_DIR/isMounted;
    mount -o remount,nosuid /data;
  else
    chroot $BOOT_DIR /init.sh; ret=$?;
  fi; exit $ret;
}

main()
{
  if [ $# -lt 2 ]; then
    show_help;
    exit $NO_ERROR;
  fi;

  check_env;
  case "$1" in
  "init")
    termix_init;
    ;;
  "boot")
    termix_boot;
    ;;
  *)
    show_help;
    exit $NO_ERROR;
    ;;
  esac
}

main "$@";
